### ISSUE TITLE
Load-testing in staging for relaunch of large "Omnibus" experiment

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1084]
Relates to: https://github.com/CarnegieLearningWeb/UpGrade/issues/1089

Currently staging is set up with production clone database from Monday Oct 23rd. It has been set up to mirror resources and auto-scaling. We should do as much load-testing variations as we can and attach results here while it is set up this way.

For running the tests, use the updated scripts on `hotfix/split-queries-for-latency-issue909` branch. 

Use v4 to compare v5 performance of assignment:

- [ ] Test `release/v4.1` with all experiments set to enrolling, no omnibus
- [ ] Test `release/v4.1` with all experiments set to enrolling, include omnibus

- [ ] Test `release/v5.0` with all experiments set to enrolling, no omnibus
- [ ] Test `release/v5.0` with all experiments set to enrolling, include omnibus

- [ ] Test `hotfix/split-queries-for-latency-issue909` with all experiments set to enrolling, no omnibus
- [ ] Test `hotfix/split-queries-for-latency-issue909` with all experiments set to enrolling, include omnibus

**Comment by danoswaltCL** [comment]
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/322110e1-476b-4f3b-bc58-60d807e405bd)

That's 2.5k requests per minute average, or 42 requests per second. We probably want to stress it up to 10k rpm or more, so like 166 rps?

Playing around with it, I think about 1200 concurrent users is the way to achieve this with our locust script.

**Comment by danoswaltCL** [comment]
went with 600 concurrent users for initial tests, although have also pushed this up to 3000 on Pratik's hotfix branch, which pushed the requests per minute up to around 18k+, around double the peak rpm load we've observed. When Omnibus experiment is not enrolling, the environment seemed to handle the increased load well until close to the peak concurrency, with the 90% percentile staying under 250ms for assign calls. With Omnibus enrolling, it was too high pretty quickly with that concurrency and spawn rate.

https://docs.google.com/document/d/1YY5CllMM87Y1k3hg23KPH5KPVZ7xKVGUo_QbNyiePBs/edit

**Comment by danoswaltCL** [comment]
Round 1: General testing to discover the difference between branches, cache-enablement, and find some baselines to do more testing:
https://gist.github.com/danoswaltCL/0ebb29f49122d080b54e9cba49816559

Round 2: Refactored testing script to parameterize who marks assignments and how often, specifically to more closely the tailor the tests specifically emulate running the "Omnibus" experiment.
https://gist.github.com/danoswaltCL/73f59a4cdd40779803d335420a649df3

Round 3: Shortening the TTL of cache manager to 1, 5, 10, and 20 seconds.
https://gist.github.com/danoswaltCL/d0a773f269a3c143899adad751885ac7
