### ISSUE TITLE
Current issues with the state of production

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1093]
Current issues with the state of production (5.0.x):

Errors can be seen here:
https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/NzMyNTEzfEFQTXxBUFBMSUNBVElPTnw4MzYyNzA4NTY?duration=2592000000&state=64704018-c039-4a7b-62ea-aedaa808e585

- [ ] `BadRequestError` https://github.com/CarnegieLearningWeb/UpGrade/issues/1092
        Risk: Errors pile up in quick succession and cause code response times runaway up to double-digit response times. Cause is not yet found.
        Priority: High (potentially a hotfix)
        
- [ ]  `getValidExperiments` latency
        https://github.com/CarnegieLearningWeb/UpGrade/issues/1089
        https://github.com/CarnegieLearningWeb/UpGrade/issues/1078
        https://github.com/CarnegieLearningWeb/UpGrade/issues/1084
        Risk: UpGrade not performant enough in `assign` and `mark` calls to run large experiments with many decision points 
        Priority: High (potentially a hotfix) in order to relaunch "Omnibus" experiment
        
- [ ]  "Enrollment Complete" is causes poor performance
        https://github.com/CarnegieLearningWeb/UpGrade/issues/909
        Risk: Cannot set experiments to "Enrollment Complete"
        Priority: High
        
- [ ]  Multiple ExperimentUserService calls use TypeOrm .save, which sometimes results in an error that looks like:
        `duplicate key value violates unique constraint "PK_bb6db004eeb82db68de9225e877`
         https://github.com/CarnegieLearningWeb/UpGrade/issues/1044
         For reference: https://github.com/CarnegieLearningWeb/UpGrade/issues/710
         Note: this error happens silently in `userAlias` call because of fix in 710, but it still can be observed happening in the postgres database logs in AWS
         Risk: This seems to tie up the DB with extra waits, which is often inconsequential when the db is calm, but can aggravate the response times when the db is working harder
        
- [ ]  Within-subjects `monitored_decisiont_point` query is very slow:
        https://github.com/CarnegieLearningWeb/UpGrade/issues/1063
        Note: Within-subjects has been temporarily made unavailable in the UI
        Risk: UpGrade cannot run within-subjects experiments
        Priority: ? Cannot run within-subjects experiments until fixed
        
- [ ]  `Cannot read property 'id' of null` happens intermittently in `log`
        https://github.com/CarnegieLearningWeb/UpGrade/issues/711
        Risk: This does not appear to have horrible effects, but it is noise and unhandled and while it doesn't appear to represent data loss, it is happening enough that we should make sure that this is a true hypothesis.
        Priority: ?
 
- [ ] #1157
        No open issue.
        Risk: We see this "error" happening all the time in production logs. It's not truly an error, and it's very noisy. While this is an entirely expected thing to see from time to time, I'm not sure we know why this happens so much from Mathia, it may be worth investigating to make sure we aren't losing user data.
        Priority: ?
        
- [ ] #1156
        Needs issue, I am just noticing this one, it is at `api/log`, this may be Mathstream?
        https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/NzMyNTEzfEFQTXxBUFBMSUNBVElPTnw4MzYyNzA4NTY?duration=2592000000&state=11c0019a-e151-bf74-47b0-2f156dfe9965
        
- [x] #1158
        Needs issue, this is an error that is related to calls that may be happening when the UI tries a couple of calls before the auth window opens; it doesn't hurt anything but it's a little noisy in the logs and indicates that some useless calls are being generated by the UI that may need to be revised so that they don't fire if the user auth flow will need to be initiated first.
        
|---- Other things to keep in mind --------------------------------------------|
        
- [ ] Error logging temporarily turned off.
       - https://github.com/CarnegieLearningWeb/UpGrade/issues/1080
       Risk: The risk that was mitigated was that the user could try to open the "Errors" tab in the UI, which will kick off a query in the errors column of the DB. Currently there is a way too much data in this table for the query it is trying to run. With it off, the risk is that experimenters won't have a view into errors. We need to remember to clear the database and turn this feature back on.
       
- [ ] Validation turned off as a response to errors in production to API requests that had previously been valid.
     https://github.com/CarnegieLearningWeb/UpGrade/issues/1043
     Risk: We should turn this back on after carefully retesting validation to make sure models are correct.
     
- [ ] Too few eyeballs monitoring production issues.
       No issue created, but we should be cross-training and making sure to have alerts / dashboards / access set up so this responsibility can be shared.
       
- [ ] Within-Subjects experiments feature needs fully tested.

- [ ] Factorial experiments feature needs fully tested.

**Comment by amurphy-cl** [comment]
Closing as old, many of these have been resolved.
