### ISSUE TITLE
Epic: Data export tasks

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1184]
The current "Simple" data export needs some updates, such as including additional experiment information, and ability to accommodate new features such as within-subjects data. We also want to investigate making changes to the feature so data is more easily accessible to users (e.g. via email attachment vs. web link)

- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1182
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1183
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1075
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/950
