### ISSUE TITLE
Epic: Roster Integration: Phase 1

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1469]
Phase 1 development will focus on integration with the [clever API](https://dev.clever.com/docs/working-with-the-clever-api).
We will create a POC that can be deployed and demonstrated using a simple client app...

Resources:
[clever data model](https://dev.clever.com/v2.1/docs/data-model)
[task document](https://docs.google.com/spreadsheets/d/1WWBYk4MSxefKK5eFJMpRoPeYGDFjcsAY1QxZTGNLuus/edit#gid=0)
[OneRoster](https://www.imsglobal.org/sites/default/files/spec/oneroster/v1p2/rostering-informationmodel/OneRosterv1p2RosteringService_InfoModelv1p0.html)

UpGrade backend changes:
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1504
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1505

New Roster Sync application:
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1506
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1507
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1509
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1511
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1512
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1514

Infrastructure:
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1515
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/1516
