### ISSUE TITLE
Frontend Unit Tests for new stuff

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1792]
The new feature-flag and common component library deserve some proper unit tests, and we should move towards making this an expectation for most PRs as a habit going forward.

The goal should be to achieve at least 80% coverage in the following directories, in this order of priority:

- [ ] shared-component-library
- [ ] shared/services
- [ ] core/feature-flags 
- [ ] dashboard/feature-flags

 With copilot and other AI tools, this is should be much easier, so 90%+ should be maybe the standard.

One big h1-sized point I'd like to offer from years of Angular testing hell: Make life easy on yourself:
# Please kindly ignore Angular's out-of-the-box TestBed-based boilerplate.

What's the TestBed for? It's there so you can use the Angular framework in your tests to make it possible to test all the parts of the component, including logic in the html, css styles, and Angular lifecycle things like change-detection.

```
beforeEach(async(() => {
    TestBed.configureTestingModule({. <---- misery
      declarations: [LoginComponent],
      imports: [TestingModule],
      providers: [AuthService, SettingsService],
    }).compileComponents();
  }))
```

Plain jest tests that cover our vanilla javascript functions in a side-effect-free way is plenty good enough for solid, reliable, easy-to-read-and-maintain tests. From experience, getting TestBed involved balloons the complexity of everything to the point that it's not worth the investment.

Sometimes there are definitely reasons to use TestBed, I'm not going say don't use it ever and for some tests you might have to to avoid doing something even weirder. I just want to say I-told-you-so now if later those tests break constantly and give no useful real feedback.

I also suggest this basic template for keeping the tests standardized across the frontend, no matter if we are testing components, services, ngrx store stuff, so it's easy to find stuff and scan the tests.

- Describe block closure for all tests for a given class / file
- Describe block closure for each function, in the order they appear in the class or file, prepended with `#` like `#initializeForm` so that it's easy to find that code block. (otherwise searching for `initializeForm` will show every instance of that method reference)

```
describe('Component', () => { // encapsulate the whole thing with describe closure

   // setup mocks and spies that are used for everything

   beforeEach(() => {
     // anything that needs set up or reset each time for every test
   });

   afterEach(() => {
     // anything that needs torn down after every test
   });

   describe('#functionName', () => {
      // mock or spy stuff that is specific to #functionName' tests

      beforeEach(() => {
         // anything that needs set up or reset each time for each "#functionName" test
      });

      afterEach(() => {
        // anything that needs torn down for each "#functionName" test
      });
   });
})

```
