### ISSUE TITLE
6.0 prod checklist

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#2120]
Last tests in staging:
- [ ] test changing migration name in staging (`revertIndividualExclusionGroupId1715937232092` to `removeGroupIdFromIndividualExclusion1721124249413`)
- [ ] swap in prod-data-db
- [ ] validate that the app will start-up
- [ ] one more round of load-tests with the prod volume

Prepare for new version:
- [ ] (if this fix worked ^) manually rename migration `revertIndividualExclusionGroupId1715937232092` to `removeGroupIdFromIndividualExclusion1721124249413` so that it will re-run sql that has already run
- [ ] remove `METRICS` config var in beanstalk prod entirely (will add new context-based metrics manually) so that it won't fail trying to seed with the "old" metrics definitions
- [ ] temporarily halt the metrics lambda trigger so that we can apply new metrics changes without losing events
- [ ] create release in Github so it shows latest as `6.0.x`

Deploy:
- [ ] deploy backend `6.0.5` via AWS beanstalk application page
- [ ] validate that it starts up without failure
- [ ] deploy frontend via Github Action
- [ ] smoke test a feature flag
- [ ] update the metrics definitions, either via UI or postman (attach the object here!)
- [ ] restart the lambda so that backlogged metrics from downtime will now be `/log` without being dropped
- [ ] validate that metrics are coming through with the new definition
- [ ] try a smaller-sized export to smoke test exports
