### ISSUE TITLE
[EPIC] Context Metadata Phase 1

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#376]
UpGrade requires some amount of coordination between the software development team working on an app and the researcher defining an experiment in UpGrade. The researcher needs to input decision points and IDs when defining an experiment, but there is no way for the researcher to know whether that point and ID exist, and it is easy to make a typo on these kinds of IDs. UpGrade will provide functionality for an app software development team to provide metadata about valid decision points so that they may be validated against an experiment.

[Context Metadata Model](https://gist.github.com/danoswaltCL/2db2b62e09550a39f7cb02d725cf0290)
**[Specification Document](https://docs.google.com/document/d/13SvJajnCcH0cqMD7gPqb5MWmynzJrVqmD5a5tooPeNo/edit?usp=sharing)**

This list will be revised to include only Phase 1 work.

- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/402
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/404
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/406
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/407
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/62
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/153
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/26
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/99
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/386
