### ISSUE TITLE
UI enhancements and bug fixes for the Experiment Stepper

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#505]
## All Steps
- [x] Correct labels/placeholders ([#470]( https://github.com/CarnegieLearningWeb/UpGrade/pull/470))
- [x] Set equal font size and style for checkbox labels ([#482]( https://github.com/CarnegieLearningWeb/UpGrade/pull/482))
- [x] Remove default rows ([#498]( https://github.com/CarnegieLearningWeb/UpGrade/pull/498))
- [x] Disable autocomplete suggestions ([#501]( https://github.com/CarnegieLearningWeb/UpGrade/pull/501))

## Overview Step
- [x] Set the equal vertical spacing between the fields ([#506]( https://github.com/CarnegieLearningWeb/UpGrade/pull/506))

## Design Step
- [x] Change the title font size to 18 ([#486]( https://github.com/CarnegieLearningWeb/UpGrade/pull/486))
- [x] Correct the vertical spacing between the title and the table ([#486]( https://github.com/CarnegieLearningWeb/UpGrade/pull/486))
- [x] Correct the table column widths ([#484]( https://github.com/CarnegieLearningWeb/UpGrade/pull/484))
- [x] Right-align the weight field's text ([#484]( https://github.com/CarnegieLearningWeb/UpGrade/pull/484))
- [x] Change the weight field's input type to `number` ([#499]( https://github.com/CarnegieLearningWeb/UpGrade/pull/499))
- [x] Correct the `scrollHeight` so the entire row is visible when added ([#486]( https://github.com/CarnegieLearningWeb/UpGrade/pull/486))
- [x] Make validation error messages more vertically compact ([#486]( https://github.com/CarnegieLearningWeb/UpGrade/pull/486))
- [x] Make the `Target` field required ([#499]( https://github.com/CarnegieLearningWeb/UpGrade/pull/499))

## Participants Step
- [x] Change the title font size to 18 ([#493]( https://github.com/CarnegieLearningWeb/UpGrade/pull/493))
- [x] Correct the vertical spacing between the title and the table ([#493]( https://github.com/CarnegieLearningWeb/UpGrade/pull/493))
- [x] Correct the table column widths ([#493]( https://github.com/CarnegieLearningWeb/UpGrade/pull/493))
- [x] Remove underline from dropdowns ([#493]( https://github.com/CarnegieLearningWeb/UpGrade/pull/493))
- [x] Correct the `scrollHeight` so the entire row is visible when added ([#493]( https://github.com/CarnegieLearningWeb/UpGrade/pull/493))
- [x] Remove unfilled rows in the UI (temporary solution) ([#498]( https://github.com/CarnegieLearningWeb/UpGrade/pull/498))
- [ ] Show a validation message if there's any unfilled row

## Metrics Step
- [x] Change the title font size to 18 ([#503]( https://github.com/CarnegieLearningWeb/UpGrade/pull/503))
- [x] Correct the vertical spacing between the title and the table ([#503]( https://github.com/CarnegieLearningWeb/UpGrade/pull/503))
- [x] Correct the table column widths ([#503]( https://github.com/CarnegieLearningWeb/UpGrade/pull/503))
- [x] Correct the `scrollHeight` so the entire row is visible when added ([#503]( https://github.com/CarnegieLearningWeb/UpGrade/pull/503))
- [x] Change the fields/autocomplete font size to `ft-14-400` just like the other steps ([#503]( https://github.com/CarnegieLearningWeb/UpGrade/pull/503))
- [ ] Vertically align the rows within a cell to the top instead of the center when `masteryWorkspace` is selected

## Post Rule Step
- [x] Unbold the dropdown text ([#506]( https://github.com/CarnegieLearningWeb/UpGrade/pull/506))
