### ISSUE TITLE
Add edit mode to the tables in the experiment stepper

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#548]
## Problems with the current table
* It's easy for the user to change something in a table by mistake
* It's harder to validate the table values since empty/unfilled rows can exist

## Solutions
* Add edit mode so that a table can only be edited on edit mode
* A row can be validated/updated as the user clicks the "Save" icon/button
* A row editing can be canceled if the user clicks the "Cancel" icon/button
* While on edit mode, the user won't be able to edit other rows or move to the next/previous step

## Reference
[Material Table Editable Examples](https://material-table.com/#/docs/features/editable) (scroll to the bottom of the page)

## Figma Prototype
[The latest UI Prototype](https://www.figma.com/file/uYxnCT2dXTftSZKFQ00Q0y/UpGrade-UI-Prototype-(latest))

## Screenshots
<img width="500" alt="Experiments - Add Experiment-02-01" src="https://user-images.githubusercontent.com/90279765/192312049-41c8e34d-bd8e-45d5-9c74-c616cebce57d.png">
<img width="500" alt="Experiments - Add Experiment-02-02" src="https://user-images.githubusercontent.com/90279765/192312064-b083a134-316f-407e-b078-7f7c263f4022.png">
<img width="500" alt="Experiments - Add Experiment-02-03" src="https://user-images.githubusercontent.com/90279765/192312076-e8274bb5-2fb4-47d6-8430-57c39326aa87.png">
<img width="500" alt="Experiments - Add Experiment-02-04" src="https://user-images.githubusercontent.com/90279765/192312199-ced55500-7ee5-41a5-9636-30c2bd680514.png">
<img width="500" alt="Experiments - Add Experiment-02-05" src="https://user-images.githubusercontent.com/90279765/192312239-3b84f54e-d533-4bbf-b34a-19dcea28fe66.png">
<img width="500" alt="Experiments - Add Experiment-02-06" src="https://user-images.githubusercontent.com/90279765/192312258-330d19b2-7ff2-4ba3-9814-bf49e1ae89bc.png">
<img width="500" alt="Experiments - Add Experiment-02-07" src="https://user-images.githubusercontent.com/90279765/192312269-61d50b8f-9c7f-4095-8ee6-ece08cf75963.png">

## Todos
- [ ] Add edit mode to the decision points and conditions tables in the Design step
- [ ] Add edit mode to the include and exclude tables in the Participants step
- [ ] Add edit mode to the metrics table in the Metrics step

**Comment by danoswaltCL** [comment]
Closing as we're winding down enhancements to stepper in favor of replacement in redesign
