### ISSUE TITLE
🗻 Stratified Random Sampling Planning

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#956]
Duration: 6 weeks

Start Date: 
Code Freeze:
QA:
Release:
Board of Truth: [Cycle 2](https://github.com/orgs/CarnegieLearningWeb/projects/1/views/11)

Included Issues:

** Note! This an incomplete list of the actual tasks, it still needs updated to reflect the board

UI DESIGN
- [x] #958

FRONTEND
- [x] #969
- [x] #964
- [x] #965
- [x] #968
- [x] #966
- [x] #971 
- [x] #967 
- [ ] UI changes for defining the strata within the experiment stepper
- [ ] Update metrics to display strata (?)

BACKEND
- [ ] Backend changes: [New Service for operations find/update/insert](https://github.com/CarnegieLearningWeb/UpGrade/issues/961)
- [ ] Backend changes: [Controller with endpoint for the csv upload](https://github.com/CarnegieLearningWeb/UpGrade/issues/962)
- [ ] Backend changes: [Controller with endpoint to get existing stratification data](https://github.com/CarnegieLearningWeb/UpGrade/issues/963)
- [ ] Create assignment algorithm for biased-coin design with multi-sided coin
- [ ] Backend changes: Update ExperimentAssignmentService to calc assignment based on stratification
- [ ] Backend changes Update ExperimentAssignmentService to factor in stratification state for mark
- [ ] Update group to accept keys and values for stratification factors
- [ ] Update assign call for SRS condition assignment

DATABASE / MODEL UPDATES
- [ ] Backend changes: [create a stratification data model](https://github.com/CarnegieLearningWeb/UpGrade/issues/959)
- [ ] Backend changes: [New table in the DB](https://github.com/CarnegieLearningWeb/UpGrade/issues/960)

CLIENT LIBRARY
- n/a

OTHER (Lambdas, infrastructure)
- n/a

Shaping document: https://docs.google.com/document/d/1CwP7ugHVy9aG-KfXUVSv9z7fuWzq-XsmCQCwrtBqxic/edit
Scoping/Verticals document: https://docs.google.com/document/d/1SvuwkGsgjJZhRN7a0rzoCt6n2F3JuO3QmZa0DYo5jZY/edit

**Comment by danoswaltCL** [comment]
@mswartzCL @amurphy-cl should this be an "epic"?

**Comment by amurphy-cl** [comment]
@danoswaltCL I created a label with an epic name, but am wondering if all epics should just be labeled "epic" with issues just linked to the epic issue number. LMK which works better for you/the team

**Comment by danoswaltCL** [comment]
maybe a @mswartzCL question! just want to be able to easily differentiate it in the list

**Comment by ppratikcr7** [comment]
@danoswaltCL Is QA done for this? Can we close all the stratification open tickets if they are done with QA?
